version: '3'

services:
  find-a-friend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=api_find_a_friend